version: '3.7'

services:
  mysql_55:
    container_name: 'mysql-5.5'
    image: 'mysql:5.5'
    restart: 'unless-stopped'
    command:
      - '--character-set-server=utf8'
      - '--collation-server=utf8_general_ci'
      - '--max-allowed-packet=1073741824'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '33055:3306'
    volumes:
      - './volumes/mysql/5.5:/var/lib/mysql'



  mysql_57:
    container_name: 'mysql-5.7'
    image: 'mysql:5.7'
    restart: 'unless-stopped'
    command:
      - '--character-set-server=utf8'
      - '--collation-server=utf8_general_ci'
      - '--max-allowed-packet=1073741824'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '33057:3306'
    volumes:
      - './volumes/mysql/5.7:/var/lib/mysql'



  pgsql_96:
    container_name: 'postgres-9.6'
    image: 'postgres:9.6'
    restart: 'unless-stopped'
    environment:
      POSTGRES_PASSWORD: 'password'
    ports:
      - '54096:5432'
    volumes:
      - './volumes/postgres/9.6:/var/lib/postgresql/data'


  pgsql_11:
    container_name: 'postgres-11'
    image: 'postgres:11'
    restart: 'unless-stopped'
    environment:
      POSTGRES_PASSWORD: 'password'
    ports:
      - '54011:5432'
    volumes:
      - './volumes/postgres/11:/var/lib/postgresql/data'



  mailhog:
    container_name: 'mailhog'
    image: mailhog/mailhog
    restart: 'unless-stopped'
    ports:
      - '1025:1025'
      - '8025:8025'



  portainer:
    container_name: 'portainer'
    image: portainer/portainer-ce
    restart: 'unless-stopped'
    command:
      - '--admin-password-file=/tmp/admin_password'
    ports:
      - '9009:9000'
      - '9008:8000'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './volumes/portainer/admin_password:/tmp/admin_password'
